config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  TYPES = %w[chinese italian japanese french belgian]
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: TYPES }
end

app/models/review.rb
class Review < ApplicationRecord
  STARS = [0, 1, 2, 3, 4, 5]
  belongs_to :restaurant
  validates :restaurant, presence: true
  validates :content, presence: true
  validates :rating, numericality: { only_integer: true }, inclusion: { in: STARS }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to(Restaurant.last)
    else
      render 'new'
    end
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review.restaurant = @restaurant
    if @review.save
    redirect_to restaurant_path(@restaurant)
    else
      render 'new'
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>

  <%= f.label :category %>
  <%= f.select :category, collection: Restaurant::TYPES %>

  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<h1 class="my-3"><%= @restaurant.name %></h1>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/index.html.erb
<div class="container">
<h1 class="mx-auto mt-5">RESTAURANTS</h1>
<ul>
<% @restaurants.each do |restaurant| %>
  <div class="list-inline">
  <li class="list-inline-item"><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
  <li class="list-inline-item"><%= restaurant.address %></li>
  <li class="list-inline-item"><%= restaurant.category %></li>
  <li class="list-inline-item"><%= restaurant.phone_number %></li>
  </div>
<% end %>
</ul>
<%= link_to "Add Restaurant", new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<h1 class="my-3">NEW RESTAURANT</h1>

<%= render 'form', restaurant: @restaurant %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<h2><%= @restaurant.category %></h2>
<h3><%= @restaurant.address %></h3>
<h4><%= @restaurant.phone_number %></h4>
<h2>REVIEWS</h2>
<% @restaurant.reviews.each do |review|%>
<p><%= "🌟" * review.rating %></p>
<h5><%= review.content %></h5>
<% end %>

<%= link_to "Edit", edit_restaurant_path(@restaurant), class: "btn btn-primary"%>
<%= link_to "Review this Restaurant", new_restaurant_review_path(@restaurant), class: "btn btn-primary"%>
<%= link_to "Back to list", restaurants_path, class: "btn btn-primary"%>
<%= link_to "Delete", restaurant_path, method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-primary"%>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.select :rating, stars: Review::STARS %>
  <%= f.submit "add a review", class: "btn btn-primary" %>
<% end %>